kind:        deployment
api_version: v1beta1
name:        Mandanov

inventory:
  hosts:
  - name:        compute-1:
    data:
      ip_address:  192.168.100.21/24

  - name:        compute-2
    data:
      ip_address:  192.168.100.22/24

  groups:
  - name:         group-1
    members:
    - compute-1
    - compute-2
    data:
      ssh_user:     secrets/ssh_user
      ssh_password: secrets/ssh_password
      gateway:      192.168.100.1
      nameservers:
      - 1.1.1.1
      - 8.8.8.8
      - 8.8.4.4

blueprints:
- kind:        hypervisor.kvm
  api_version: v1beta1
  # This blueprint is different from the other blueprints becau
  # This will contain a declaration of the hypervisor hosts
  # and which of the hosts (VMs) declared in the above inventory
  # belong where. This is going to be an odd blueprint because
  # whereas all other blueprints will use the above inventory
  # to determine which servers to configure, this one will have
  # it's own inventory and will use the above inventory to
  # determine where to create them. I wonder if that's a sign
  # of scope screep.
  hypervisors:
    - host: kvm-1
      guests:
        - compute-1
        - compute-2

    - host: kvm-2
      guests:
        - compute-3

- kind:        cicd.gitlab
  api_version: v1
  data:
    # This will contain a declaration of which groups are servers
    # and which ones are runners. It will also contain all other
    # data needed by the blueprint to install gitlab
    servers:
      - host: compute-1
    runners:
      - host: compute-2

- kind:        lma.prometheus
  api_version: v1beta1
  data:
    # This will contain a declaration of which servers will host
    # prometheus plus all other data needed to intall prome.
    ...
